// Portado verbatim de OrcamentoARA.jsx (Caminho A) — plano de contas, pacotes
// e centros de custo oficiais da ARA Têxtil (fonte: Matriz_Governanca_OBZ_2027_4.xlsx
// e consulta CTT010). Não editar aqui sem editar também o .jsx (ou, quando a
// Fase 6 aposentar o protótipo, tratar isto como única fonte). Ver seed
// equivalente em ../../db/seed_referencia.sql (mesmos dados, para consulta
// pelo backend sem round-trip ao banco).

export const MESES = ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'];
export const mesesVazios = () => Array(12).fill('');

export const PRODUTOS_REF = [
  { nome: 'ALGODAO PENTEADO 1,20', volumeRef: 405, precoRef: 41.70 },
  { nome: 'COTTON LIGHT', volumeRef: 495, precoRef: 47.50 },
  { nome: 'COTTON SOFT', volumeRef: 230, precoRef: 43.50 },
  { nome: 'L20', volumeRef: 201, precoRef: 27.25 },
  { nome: 'MALHA UV', volumeRef: 354, precoRef: 26.50 },
  { nome: 'PVN', volumeRef: 126, precoRef: 23.59 },
  { nome: 'SUPLEX', volumeRef: 1726, precoRef: 28.30 },
  { nome: 'UV CONFORT', volumeRef: 241, precoRef: 28.50 },
  { nome: 'BAIXO GIRO', volumeRef: 423, precoRef: 19.80 },
];

export const DEDUCOES_REF = [
  { id: 'pis', nome: 'PIS', pctRef: 1.47 },
  { id: 'cofins', nome: 'Cofins', pctRef: 6.75 },
  { id: 'icms_pe', nome: 'ICMS Pernambuco', pctRef: 7.00 },
  { id: 'icms_for', nome: 'ICMS Fortaleza', pctRef: 12.00 },
  { id: 'cancelamentos', nome: 'Cancelamentos', pctRef: 3.00 },
];

// Nível de subárea (14 CCs) — fonte: extrato CTT010 fornecido pelo usuário
// em 2026-08-19 (código, descrição, responsável), resolvendo a pendência
// registrada desde a Fase 1 ("granularidade do CC: usando nível de área —
// confirmar se deve descer ao nível de subárea"). Substitui o nível de área
// anterior (8 CCs, códigos 00401/00402/... — histórico, não usar mais).
// tipo: prefixo 001./002. = despesa (apoio/comercial), 004. = produção —
// mesma lógica de classificação da lista anterior.
export const CCS_TEXTIL = [
  { codigo: '001.0101', nome: 'Administração - Apoio', tipo: 'despesa' },
  { codigo: '001.0105', nome: 'Tecnologia da Informação', tipo: 'despesa' },
  { codigo: '001.0109', nome: 'Logística', tipo: 'despesa' },
  { codigo: '002.0101', nome: 'Vendas', tipo: 'despesa' },
  { codigo: '002.0102', nome: 'Marketing', tipo: 'despesa' },
  { codigo: '002.0103', nome: 'Fashion', tipo: 'despesa' },
  { codigo: '004.0101', nome: 'Malharia', tipo: 'producao' },
  { codigo: '004.0199', nome: 'Manutenção Malharia', tipo: 'producao' },
  { codigo: '004.0201', nome: 'Beneficiamento', tipo: 'producao' },
  { codigo: '004.0299', nome: 'Manutenção Beneficiamento', tipo: 'producao' },
  { codigo: '004.0301', nome: 'Apoio Produção', tipo: 'producao' },
  { codigo: '004.0302', nome: 'Qualidade Processo & Produto', tipo: 'producao' },
  { codigo: '004.0303', nome: 'Infra Estrutura', tipo: 'producao' },
  { codigo: '004.0304', nome: 'ETE', tipo: 'producao' },
];

export const PACOTES_TEXTIL = [
  { id: 'pessoal', nome: 'Pessoal', ref: 'Matriz_Governanca_OBZ_2027_4 (43 contas)' },
  { id: 'producao', nome: 'Produção', ref: 'Matriz_Governanca_OBZ_2027_4 (12 contas)' },
  { id: 'manutencao', nome: 'Manutenção', ref: 'Matriz_Governanca_OBZ_2027_4 (13 contas)' },
  { id: 'fretes', nome: 'Fretes e Logística', ref: 'Matriz_Governanca_OBZ_2027_4 (8 contas)' },
  { id: 'servicos', nome: 'Serviços de Terceiros', ref: 'Matriz_Governanca_OBZ_2027_4 (11 contas)' },
  { id: 'comercial', nome: 'Comercial e Marketing', ref: 'Matriz_Governanca_OBZ_2027_4 (2 contas)' },
  { id: 'viagens', nome: 'Viagens', ref: 'Matriz_Governanca_OBZ_2027_4 (3 contas)' },
  // Nomenclatura padronizada em 2026-08-31 — espelho de frontend/src/OrcamentoARA.jsx.
  { id: 'locacao', nome: 'Locação e Ocupação', ref: 'Matriz_Governanca_OBZ_2027_4 (17 contas)' },
  { id: 'depreciacao', nome: 'Depreciação e Amortização', ref: 'Matriz_Governanca_OBZ_2027_4 (10 contas)' },
  { id: 'administrativo_utilidades', nome: 'Administrativo e Utilidades', ref: 'Matriz_Governanca_OBZ_2027_4 (43 contas)' },
  { id: 'impostos', nome: 'Impostos Indiretos e Diretos', ref: 'Matriz_Governanca_OBZ_2027_4 (5 contas)' },
];

// De-para oficial conta contábil -> Pacote (Matriz_Governanca_OBZ_2027_4). Ver
// db/seed_referencia.sql para o mesmo conteúdo carregado na tabela `contas`.
export const PLANO_CONTAS = {
  pessoal: [
    { codigo: '71101001', nome: 'SALARIOS E ORDENADOS', origem: 'Custo' },
    { codigo: '71101002', nome: 'PREMIOS E GRATIFICACOES', origem: 'Custo' },
    { codigo: '71101003', nome: 'HORAS EXTRAS', origem: 'Custo' },
    { codigo: '71101004', nome: 'FERIAS E ABONO', origem: 'Custo' },
    { codigo: '71101005', nome: '13º SALARIO', origem: 'Custo' },
    { codigo: '71101006', nome: 'INSS (GPS)', origem: 'Custo' },
    { codigo: '71101007', nome: 'FGTS (GFIP)', origem: 'Custo' },
    { codigo: '71101008', nome: 'INDENIZACOES E AVISO PREVIO', origem: 'Custo' },
    { codigo: '71101009', nome: 'VALE ELETRONICO (VEM)', origem: 'Custo' },
    { codigo: '71101010', nome: 'CESTAS BASICAS', origem: 'Custo' },
    { codigo: '71101011', nome: 'FARDAMENTOS - EPI', origem: 'Custo' },
    { codigo: '71101012', nome: 'ASSISTENCIA MEDICA E SOCIAL', origem: 'Custo' },
    { codigo: '71101013', nome: 'DESPESAS COM TREINAMENTO DE PESSOAL', origem: 'Custo' },
    { codigo: '71101014', nome: 'PENSAO ALIMENTICIA', origem: 'Custo' },
    { codigo: '71102098', nome: 'RATEIO - MAO DE OBRA', origem: 'Custo' },
    { codigo: '34101001', nome: 'ORDENADOS E SALARIOS', origem: 'Despesa' },
    { codigo: '34101002', nome: 'PREMIOS E GRATIFICACOES', origem: 'Despesa' },
    { codigo: '34101003', nome: '13º SALARIO', origem: 'Despesa' },
    { codigo: '34101004', nome: 'FERIAS', origem: 'Despesa' },
    { codigo: '34101005', nome: 'INSS (GPS)', origem: 'Despesa' },
    { codigo: '34101006', nome: 'FGTS (GFIP)', origem: 'Despesa' },
    { codigo: '34101007', nome: 'INDENIZACOES E AVISO PREVIO', origem: 'Despesa' },
    { codigo: '34101008', nome: 'VALE ELETRONICO (VEM)', origem: 'Despesa' },
    { codigo: '34101009', nome: 'CESTAS BASICAS', origem: 'Despesa' },
    { codigo: '34101010', nome: 'FARDAMENTOS - EPI', origem: 'Despesa' },
    { codigo: '34101011', nome: 'ASSISTENCIA MEDICA E SOCIAL', origem: 'Despesa' },
    { codigo: '34101012', nome: 'DESPESAS COM TREINAMENTO DE PESSOAL', origem: 'Despesa' },
    { codigo: '34101014', nome: 'HORAS EXTRAS', origem: 'Despesa' },
    { codigo: '34201001', nome: 'ORDENADOS E SALARIOS', origem: 'Despesa' },
    { codigo: '34201002', nome: 'PREMIOS E GRATIFICACOES', origem: 'Despesa' },
    { codigo: '34201003', nome: '13º SALARIO', origem: 'Despesa' },
    { codigo: '34201004', nome: 'FERIAS', origem: 'Despesa' },
    { codigo: '34201005', nome: 'INSS (GPS)', origem: 'Despesa' },
    { codigo: '34201006', nome: 'FGTS (GFIP)', origem: 'Despesa' },
    { codigo: '34201007', nome: 'INDENIZACOES E AVISO PREVIO', origem: 'Despesa' },
    { codigo: '34201008', nome: 'VALE ELETRONICO (VEM)', origem: 'Despesa' },
    { codigo: '34201009', nome: 'CESTAS BASICAS', origem: 'Despesa' },
    { codigo: '34201010', nome: 'FARDAMENTOS - EPI', origem: 'Despesa' },
    { codigo: '34201011', nome: 'ASSISTENCIA MEDICA E SOCIAL', origem: 'Despesa' },
    { codigo: '34201012', nome: 'DESPESA COM TREINAMENTO DE PESSOAL', origem: 'Despesa' },
    { codigo: '34201013', nome: 'PENSAO ALIMENTICIA', origem: 'Despesa' },
    { codigo: '34201014', nome: 'PRO-LABORE', origem: 'Despesa' },
    { codigo: '34201015', nome: 'HORAS EXTRAS', origem: 'Despesa' },
  ],
  producao: [
    { codigo: '71102010', nome: 'MATERIA PRIMA FIO', origem: 'Custo' },
    { codigo: '71102011', nome: 'MATERIA PRIMA PRODUTOS QUIMICOS', origem: 'Custo' },
    { codigo: '71102012', nome: 'MATERIAL DE EMBALAGENS', origem: 'Custo' },
    { codigo: '71102037', nome: 'MALHA CRUA', origem: 'Custo' },
    { codigo: '72102101', nome: 'CUSTOS DIRETOS', origem: 'Custo' },
    { codigo: '72102102', nome: 'MALHARIA', origem: 'Custo' },
    { codigo: '72102103', nome: 'MOD - MAO OBRA DIRETA', origem: 'Custo' },
    { codigo: '72102104', nome: 'MATERIA PRIMA', origem: 'Custo' },
    { codigo: '72102105', nome: 'BENEFICIAMENTO', origem: 'Custo' },
    { codigo: '72102106', nome: 'MOD - MAO DE OBRA DIRETA', origem: 'Custo' },
    { codigo: '72102107', nome: 'MATERIA PRIMA', origem: 'Custo' },
    { codigo: '72102108', nome: 'EMBALAGEM', origem: 'Custo' },
  ],
  manutencao: [
    { codigo: '71102004', nome: 'MANUTENCAO, CONSERVACAO E LIMPEZA', origem: 'Custo' },
    { codigo: '71102022', nome: 'MANUTENCAO PREDIAL', origem: 'Custo' },
    { codigo: '71102033', nome: 'MANUTENCAO DE MAQ E EQUIPAMENTOS', origem: 'Custo' },
    { codigo: '34104002', nome: 'MANUTENCAO DE VEICULOS', origem: 'Despesa' },
    { codigo: '34104010', nome: 'MANUTENCAO - CONSERVACAO E LIMPEZA', origem: 'Despesa' },
    { codigo: '34104028', nome: 'MANUTENCAO DE MAQUINAS E EQUIPAMENTOS', origem: 'Despesa' },
    { codigo: '34104031', nome: 'DESPESAS COM COMBUSTIVEIS', origem: 'Despesa' },
    { codigo: '34104032', nome: 'MANUTENCAO PREDIAL', origem: 'Despesa' },
    { codigo: '34202004', nome: 'MANUTENCAO DE VEICULOS', origem: 'Despesa' },
    { codigo: '34202007', nome: 'CONSERVACAO E LIMPEZA', origem: 'Despesa' },
    { codigo: '34202026', nome: 'MANUTENCAO DE MAQ E EQUIPAMENTOS', origem: 'Despesa' },
    { codigo: '34202029', nome: 'DESPESAS COM COMBUSTIVEL', origem: 'Despesa' },
    { codigo: '34202030', nome: 'MANUTENCAO PREDIAL', origem: 'Despesa' },
  ],
  fretes: [
    { codigo: '71102009', nome: 'FRETES E CARRETOS', origem: 'Custo' },
    { codigo: '71102030', nome: 'DESPACHANTE', origem: 'Custo' },
    { codigo: '34104001', nome: 'FRETES E CARRETOS', origem: 'Despesa' },
    { codigo: '34104003', nome: 'SERVICOS ADUANEIROS', origem: 'Despesa' },
    { codigo: '34104004', nome: 'DESPACHANTE', origem: 'Despesa' },
    { codigo: '34202015', nome: 'FRETES E CARRETOS', origem: 'Despesa' },
    { codigo: '34202032', nome: 'DESPACHANTE', origem: 'Despesa' },
    { codigo: '34202040', nome: 'DESPESAS COM ARMAZENAGEM', origem: 'Despesa' },
  ],
  servicos: [
    { codigo: '71102003', nome: 'SERVICOS DE TERCEIROS - PJ', origem: 'Custo' },
    { codigo: '71102016', nome: 'ASSESSORIAS E CONSULTORIAS', origem: 'Custo' },
    { codigo: '71102017', nome: 'SERVICOS DE TERCEIROS - PESSOA FISICA', origem: 'Custo' },
    { codigo: '71102031', nome: 'SEGURANCA E VIGILANCIA', origem: 'Custo' },
    { codigo: '34104013', nome: 'SERVICOS DE TERCEIROS PESSOA JURIDICA', origem: 'Despesa' },
    { codigo: '34104025', nome: 'SEGURANCA - VIGILANCIA', origem: 'Despesa' },
    { codigo: '34104029', nome: 'ASSESSORIAS E CONSULTORIAS', origem: 'Despesa' },
    { codigo: '34202010', nome: 'SERVICOS DE TERCEIROS - PJ', origem: 'Despesa' },
    { codigo: '34202017', nome: 'SERVICOS DE TERCEIROS - PESSOA FISICA', origem: 'Despesa' },
    { codigo: '34202023', nome: 'SEGURANCA E VIGILANCIA', origem: 'Despesa' },
    { codigo: '34202027', nome: 'ASSESSORIAS E CONSULTORIAS', origem: 'Despesa' },
  ],
  comercial: [
    { codigo: '34102001', nome: 'COMISSOES', origem: 'Despesa' },
    { codigo: '34103001', nome: 'PROPAGANDA E PUBLICIDADE', origem: 'Despesa' },
  ],
  viagens: [
    { codigo: '71102026', nome: 'DESPESAS COM VIAGENS', origem: 'Custo' },
    { codigo: '34104020', nome: 'DESPESAS COM VIAGENS', origem: 'Despesa' },
    { codigo: '34202018', nome: 'DESPESAS COM VIAGENS', origem: 'Despesa' },
  ],
  locacao: [
    { codigo: '71102027', nome: 'ALUGUEL', origem: 'Custo' },
    { codigo: '71102032', nome: 'LOCACAO DE MAQUINAS E EQUIPAMENTOS', origem: 'Custo' },
    { codigo: '34104019', nome: 'LOCACAO DE PESSOA FISICA', origem: 'Despesa' },
    { codigo: '34104021', nome: 'LOCACOES E CONDOMINIOS', origem: 'Despesa' },
    { codigo: '34104027', nome: 'LOCACAO DE MAQUINAS E EQUIPAMENTOS', origem: 'Despesa' },
    { codigo: '34104035', nome: 'LOCACAO DE PESSOA JURIDICA', origem: 'Despesa' },
    { codigo: '34202019', nome: 'ALUGUEL A PESSOA FISICA', origem: 'Despesa' },
    { codigo: '34202025', nome: 'LOCACAO DE MAQ E EQUIPAMENTOS', origem: 'Despesa' },
    { codigo: '71102001', nome: 'ENERGIA ELETRICA', origem: 'Custo' },
    { codigo: '71102002', nome: 'TELEFONE', origem: 'Custo' },
    { codigo: '71102034', nome: 'DESPESAS COM GAS', origem: 'Custo' },
    { codigo: '34104005', nome: 'ENERGIA ELETRICA', origem: 'Despesa' },
    { codigo: '34104006', nome: 'AGUA E ESGOTO', origem: 'Despesa' },
    { codigo: '34104007', nome: 'TELEFONE E INTERNET', origem: 'Despesa' },
    { codigo: '34202001', nome: 'ENERGIA ELETRICA', origem: 'Despesa' },
    { codigo: '34202002', nome: 'AGUA E ESGOTO', origem: 'Despesa' },
    { codigo: '34202003', nome: 'TELEFONE E INTERNET', origem: 'Despesa' },
  ],
  depreciacao: [
    { codigo: '71102008', nome: 'ENCARGOS COM DEPRECIACAO', origem: 'Custo' },
    { codigo: '71102015', nome: 'ENCARGOS DE DEPRECIACAO -CUSTO ATRIBUIDO', origem: 'Custo' },
    { codigo: '71102023', nome: 'PIS-COFINS SOBRE DEPRECIACAO', origem: 'Custo' },
    { codigo: '34104014', nome: 'ENCARGOS DE DEPRECIACAO', origem: 'Despesa' },
    { codigo: '34104022', nome: 'PIS - COFINS SOBRE DEPRECIACAO', origem: 'Despesa' },
    { codigo: '34104026', nome: 'DEPRECIACAO - CUSTO ATRIBUIDO', origem: 'Despesa' },
    { codigo: '34104034', nome: 'DEPRECIACAO NAO DEDUTIVEL', origem: 'Despesa' },
    { codigo: '34202011', nome: 'ENCARGOS COM DEPRECIACAO', origem: 'Despesa' },
    { codigo: '34202020', nome: 'PIS / COFINS SOBRE A DEPRECIACAO', origem: 'Despesa' },
    { codigo: '34202024', nome: 'ENCARGOS DE DEPRECIACAO -CUSTO ATRIBUIDO', origem: 'Despesa' },
  ],
  administrativo_utilidades: [
    { codigo: '71101018', nome: 'ALIMENTACAO', origem: 'Custo' },
    { codigo: '71102005', nome: 'MATERIAL DE USO E CONSUMO', origem: 'Custo' },
    { codigo: '71102006', nome: 'REFEICOES', origem: 'Custo' },
    { codigo: '71102021', nome: 'CAIXA FUNDO FIXO', origem: 'Custo' },
    { codigo: '71102024', nome: 'MATERIAL DE EXPEDIENTE', origem: 'Custo' },
    { codigo: '71102025', nome: 'BENS DE PEQUENO VALOR', origem: 'Custo' },
    { codigo: '71102028', nome: 'LIVROS JORNAIS E REVISTAS', origem: 'Custo' },
    { codigo: '71102029', nome: 'CORREIOS E MALOTES', origem: 'Custo' },
    { codigo: '71102036', nome: 'DESPESAS COM FESTAS E BRINDES', origem: 'Custo' },
    { codigo: '71102096', nome: 'RATEIO - ENERGIA', origem: 'Custo' },
    { codigo: '71102097', nome: 'RATEIO  - GAS', origem: 'Custo' },
    { codigo: '71102099', nome: 'RATEIO DEMAIS PARTES', origem: 'Custo' },
    { codigo: '71102100', nome: 'RATEIO PARA BENEFICIAMENTO', origem: 'Custo' },
    { codigo: '34101015', nome: 'ALIMENTACAO', origem: 'Despesa' },
    { codigo: '34104008', nome: 'CORREIOS E MALOTES', origem: 'Despesa' },
    { codigo: '34104009', nome: 'MATERIAL DE EXPEDIENTE', origem: 'Despesa' },
    { codigo: '34104011', nome: 'LIVROS - JORNAIS E REVISTAS', origem: 'Despesa' },
    { codigo: '34104012', nome: 'DESPESAS COM ALIMENTACAO', origem: 'Despesa' },
    { codigo: '34104015', nome: 'BENS DE PEQUENO VALOR', origem: 'Despesa' },
    { codigo: '34104016', nome: 'DESPESAS COM FESTAS E BRINDES', origem: 'Despesa' },
    { codigo: '34104023', nome: 'REFEICOES', origem: 'Despesa' },
    { codigo: '34104024', nome: 'CAIXA FUNDO FIXO', origem: 'Despesa' },
    { codigo: '34104033', nome: 'MATERIAL DE USO E CONSUMO', origem: 'Despesa' },
    { codigo: '34104036', nome: 'PERDA DE RECEBIVEIS', origem: 'Despesa' },
    { codigo: '34104090', nome: 'DIVERSOS', origem: 'Despesa' },
    { codigo: '34201016', nome: 'ALIMENTACAO', origem: 'Despesa' },
    { codigo: '34202005', nome: 'CORREIOS E MALOTES', origem: 'Despesa' },
    { codigo: '34202006', nome: 'MATERIAL DE EXPEDIENTE', origem: 'Despesa' },
    { codigo: '34202008', nome: 'LIVROS, JORNAIS E REVISTAS', origem: 'Despesa' },
    { codigo: '34202009', nome: 'DESPESA  ALIMENTACAO', origem: 'Despesa' },
    { codigo: '34202012', nome: 'BENS DE PEQUENO VALOR', origem: 'Despesa' },
    { codigo: '34202013', nome: 'DESPESAS COM FESTAS E BRINDES', origem: 'Despesa' },
    { codigo: '34202021', nome: 'REFEICOES', origem: 'Despesa' },
    { codigo: '34202022', nome: 'CAIXA FUNDO FIXO', origem: 'Despesa' },
    { codigo: '34202031', nome: 'MATERIAL DE USO E CONSUMO', origem: 'Despesa' },
    { codigo: '34202034', nome: 'DESPESAS ADMINISTRATIVAS RATEADAS', origem: 'Despesa' },
    { codigo: '34202035', nome: 'DOACOES', origem: 'Despesa' },
    { codigo: '34202037', nome: 'OUTRAS DESPESAS NAO DEDUTIVEIS', origem: 'Despesa' },
    { codigo: '34202038', nome: 'OUTRAS DESPESAS OPERACIONAIS', origem: 'Despesa' },
    { codigo: '34202042', nome: 'PERDAS COM FORNECEDOR', origem: 'Despesa' },
    { codigo: '71102035', nome: 'DESPESAS COM SEGUROS', origem: 'Custo' },
    { codigo: '34104030', nome: 'DESPESAS COM SEGUROS', origem: 'Despesa' },
    { codigo: '34202028', nome: 'DESPESAS COM SEGUROS', origem: 'Despesa' },
  ],
  impostos: [
    { codigo: '71102007', nome: 'IMPOSTOS E TAXAS DIVERSAS', origem: 'Custo' },
    { codigo: '34104017', nome: 'IMPOSTOS E TAXAS', origem: 'Despesa' },
    { codigo: '34104018', nome: 'CONTRIBUICAO SINDICAL', origem: 'Despesa' },
    { codigo: '34202014', nome: 'IMPOSTOS E TAXAS', origem: 'Despesa' },
    { codigo: '34202016', nome: 'CONTRIBUICAO SINDICAL', origem: 'Despesa' },
  ],
};

// Mapa reverso conta -> pacote (idêntico ao TODAS_CONTAS do .jsx, linhas 897-901).
export const TODAS_CONTAS = {};
Object.entries(PLANO_CONTAS).forEach(([pacoteId, contas]) => {
  contas.forEach((c) => { TODAS_CONTAS[c.codigo] = { ...c, pacoteId }; });
});
