// Portado verbatim de OrcamentoARA.jsx — plano de contas e pacotes de
// ARA Agrícola e ARA Resorts (fonte: Matriz_Governanca_OBZ_2027_4.xlsx).
//
// PENDÊNCIA (decisão de 2026-08-09): estas duas unidades não têm Centro de
// Custo oficial na fonte — a matriz de governança não traz essa coluna para
// elas (só para Têxtil e Corporativo). Por decisão do usuário, o lançamento
// de orçamento foi habilitado mesmo assim, usando os mesmos 8 CCs genéricos
// da Têxtil como PLACEHOLDER (ver CCS_PLACEHOLDER_AGRICOLA_RESORTS abaixo) —
// substituir assim que houver uma planilha de CC real para cada unidade.
export const CCS_PLACEHOLDER_AGRICOLA_RESORTS = [
  { codigo: '00401', nome: 'Malharia', tipo: 'producao' }, // nome herdado da Têxtil — ajustar ao subir a planilha real
  { codigo: '00402', nome: 'Beneficiamento', tipo: 'producao' },
  { codigo: '00403', nome: 'Produção', tipo: 'producao' },
  { codigo: '00001', nome: 'Diretoria', tipo: 'despesa' },
  { codigo: '00101', nome: 'Administração', tipo: 'despesa' },
  { codigo: '00201', nome: 'Comercial', tipo: 'despesa' },
  { codigo: '00301', nome: 'Logística', tipo: 'despesa' },
  { codigo: '00999', nome: 'Apoio Geral', tipo: 'despesa' },
];

// 2026-08-20: De/Para com Camadas.xlsx (CCs da área Fazenda × conta
// analítica) revelou 4 contas reais em uso que não estavam na Matriz de
// Governança — adicionadas (71102034/71102036 em manutencao, 71102049 em
// producao, 71103001 em servicos). Ver CONTAS_POR_CC_AGRICOLA no frontend
// (whitelist por CC — só usada lá, não precisa espelhar aqui: o backend não
// valida quais contas cada CC pode usar, só qual unidade/CC o usuário pode
// escrever).
export const PACOTES_AGRICOLA = [
  { id: 'pessoal', nome: "Pessoal", ref: 'Matriz_Governanca_OBZ_2027_4 (62 contas)' },
  { id: 'administrativo_utilidades', nome: "Administrativo e Utilidades", ref: 'Matriz_Governanca_OBZ_2027_4 (29 contas)' },
  { id: 'servicos', nome: "Serviços de Terceiros", ref: 'Matriz_Governanca_OBZ_2027_4 (9 contas) + Camadas.xlsx (1 conta)' },
  { id: 'manutencao', nome: "Manutenção", ref: 'Matriz_Governanca_OBZ_2027_4 (9 contas) + Camadas.xlsx (2 contas)' },
  { id: 'impostos', nome: "Impostos Indiretos e Diretos", ref: 'Matriz_Governanca_OBZ_2027_4 (4 contas)' },
  { id: 'depreciacao', nome: "Depreciação e Amortização", ref: 'Matriz_Governanca_OBZ_2027_4 (3 contas)' },
  { id: 'fretes', nome: "Fretes e Logística", ref: 'Matriz_Governanca_OBZ_2027_4 (10 contas)' },
  { id: 'producao', nome: "Produção", ref: 'Matriz_Governanca_OBZ_2027_4 (15 contas) + Camadas.xlsx (1 conta)' },
  { id: 'comercial', nome: "Comercial e Marketing", ref: 'Matriz_Governanca_OBZ_2027_4 (4 contas)' },
  { id: 'viagens', nome: "Viagens", ref: 'Matriz_Governanca_OBZ_2027_4 (2 contas)' },
  { id: 'locacao', nome: "Locação e Ocupação", ref: 'Matriz_Governanca_OBZ_2027_4 (4 contas)' },
  { id: 'tecnologia', nome: "Tecnologia e Inovação", ref: 'Matriz_Governanca_OBZ_2027_4 (2 contas)' },
];

// CCs reais da ARA Agrícola (Plano Centro de Custo.xlsx, 2026-08-20) — 9
// áreas (nível sintético/consolidador, nivel:2) e seus CCs analíticos
// (nivel:3, areaCodigo aponta pro código da área-mãe). Mesma estrutura pras
// duas fazendas (agricola_tds/agricola_fds — ver registroUnidades.js).
// Espelho exato de CCS_AGRICOLA em frontend/src/OrcamentoARA.jsx.
export const CCS_AGRICOLA = [
  { codigo: '501', nome: 'Administrativo Financeiro', tipo: 'despesa', nivel: 2, areaCodigo: null },
  { codigo: '50101', nome: 'Adm. Financeiro', tipo: 'despesa', nivel: 3, areaCodigo: '501' },
  { codigo: '50102', nome: 'DP e SESTR', tipo: 'despesa', nivel: 3, areaCodigo: '501' },
  { codigo: '50103', nome: 'TI Software', tipo: 'despesa', nivel: 3, areaCodigo: '501' },
  { codigo: '50105', nome: 'Fiscal', tipo: 'despesa', nivel: 3, areaCodigo: '501' },

  { codigo: '502', nome: 'Operação', tipo: 'despesa', nivel: 2, areaCodigo: null },
  { codigo: '50201', nome: 'Segurança e Portaria', tipo: 'despesa', nivel: 3, areaCodigo: '502' },
  { codigo: '50202', nome: 'Oficina e Manutenção', tipo: 'despesa', nivel: 3, areaCodigo: '502' },
  { codigo: '50203', nome: 'Infra Estrutura', tipo: 'despesa', nivel: 3, areaCodigo: '502' },
  { codigo: '50204', nome: 'Transporte de Pessoal', tipo: 'producao', nivel: 3, areaCodigo: '502' },
  { codigo: '50205', nome: 'Cantina', tipo: 'despesa', nivel: 3, areaCodigo: '502' },
  { codigo: '50206', nome: 'Adm. Operação', tipo: 'despesa', nivel: 3, areaCodigo: '502' },
  { codigo: '50207', nome: 'Almoxarifado', tipo: 'despesa', nivel: 3, areaCodigo: '502' },

  { codigo: '503', nome: 'Produção', tipo: 'producao', nivel: 2, areaCodigo: null },
  { codigo: '50301', nome: 'Cabeçal 1', tipo: 'producao', nivel: 3, areaCodigo: '503' },
  { codigo: '50302', nome: 'Cabeçal 2', tipo: 'producao', nivel: 3, areaCodigo: '503' },
  { codigo: '50303', nome: 'Cabeçal 3', tipo: 'producao', nivel: 3, areaCodigo: '503' },

  { codigo: '504', nome: 'Fazenda', tipo: 'producao', nivel: 2, areaCodigo: null },
  { codigo: '50402', nome: 'Adm Fazenda', tipo: 'producao', nivel: 3, areaCodigo: '504' },
  { codigo: '50403', nome: 'Irrigação', tipo: 'producao', nivel: 3, areaCodigo: '504' },
  { codigo: '50404', nome: 'Bloco Teste Uva', tipo: 'producao', nivel: 3, areaCodigo: '504' },
  { codigo: '50405', nome: 'Bloco Teste Mirtilo', tipo: 'producao', nivel: 3, areaCodigo: '504' },

  { codigo: '505', nome: 'Packing House', tipo: 'producao', nivel: 2, areaCodigo: null },
  { codigo: '50501', nome: 'Certificações', tipo: 'producao', nivel: 3, areaCodigo: '505' },
  { codigo: '50502', nome: 'Adm PH', tipo: 'producao', nivel: 3, areaCodigo: '505' },
  { codigo: '50503', nome: 'Operações PH', tipo: 'producao', nivel: 3, areaCodigo: '505' },
  { codigo: '50504', nome: 'Embalagem', tipo: 'producao', nivel: 3, areaCodigo: '505' },

  { codigo: '506', nome: 'Comercial', tipo: 'despesa', nivel: 2, areaCodigo: null },
  { codigo: '50601', nome: 'Vendas', tipo: 'despesa', nivel: 3, areaCodigo: '506' },
  { codigo: '50602', nome: 'Marketing', tipo: 'despesa', nivel: 3, areaCodigo: '506' },
  { codigo: '50605', nome: 'Logística', tipo: 'despesa', nivel: 3, areaCodigo: '506' },
  { codigo: '50606', nome: 'Câmara Fria', tipo: 'producao', nivel: 3, areaCodigo: '506' },

  { codigo: '507', nome: 'Planejamento e Gestão', tipo: 'despesa', nivel: 2, areaCodigo: null },
  { codigo: '50701', nome: 'Invest Máquinas-Equipamentos', tipo: 'despesa', nivel: 3, areaCodigo: '507' },
  { codigo: '50702', nome: 'Invest Edificações', tipo: 'despesa', nivel: 3, areaCodigo: '507' },
  { codigo: '50703', nome: 'Invest Mudas', tipo: 'despesa', nivel: 3, areaCodigo: '507' },
  { codigo: '50704', nome: 'Invest Diversos', tipo: 'despesa', nivel: 3, areaCodigo: '507' },
  { codigo: '50705', nome: 'Projeto Pessoas', tipo: 'despesa', nivel: 3, areaCodigo: '507' },
  { codigo: '50706', nome: 'Projeto Replantio', tipo: 'despesa', nivel: 3, areaCodigo: '507' },
  { codigo: '50710', nome: 'Suprimentos', tipo: 'despesa', nivel: 3, areaCodigo: '507' },
  { codigo: '50711', nome: 'Gente e Gestão', tipo: 'despesa', nivel: 3, areaCodigo: '507' },
  { codigo: '50712', nome: 'Adm. Planejamento e Gestão', tipo: 'despesa', nivel: 3, areaCodigo: '507' },

  { codigo: '508', nome: 'Uva Terceiros', tipo: 'producao', nivel: 2, areaCodigo: null },
  { codigo: '50801', nome: 'Roberto Hirai', tipo: 'producao', nivel: 3, areaCodigo: '508' },
  { codigo: '50802', nome: 'Marcos Luiz Loureiro Alves', tipo: 'producao', nivel: 3, areaCodigo: '508' },
  { codigo: '50803', nome: 'Latitude 9', tipo: 'producao', nivel: 3, areaCodigo: '508' },
  { codigo: '50804', nome: 'Fruticultura Maria Martins Ltda', tipo: 'producao', nivel: 3, areaCodigo: '508' },
  { codigo: '50805', nome: 'Cooperativa Agrícola', tipo: 'producao', nivel: 3, areaCodigo: '508' },
  { codigo: '50806', nome: 'Frutos do Sol', tipo: 'producao', nivel: 3, areaCodigo: '508' },
  { codigo: '50807', nome: 'Aldemir de Araújo', tipo: 'producao', nivel: 3, areaCodigo: '508' },
  { codigo: '50808', nome: 'Ibatuba', tipo: 'producao', nivel: 3, areaCodigo: '508' },
  { codigo: '50809', nome: 'Nova Neruda', tipo: 'producao', nivel: 3, areaCodigo: '508' },
  { codigo: '50810', nome: 'Ednilson', tipo: 'producao', nivel: 3, areaCodigo: '508' },
  { codigo: '50811', nome: 'Marcus Vinícius Furtado Santos', tipo: 'producao', nivel: 3, areaCodigo: '508' },
  { codigo: '50812', nome: 'Colinas do Vale', tipo: 'producao', nivel: 3, areaCodigo: '508' },

  { codigo: '511', nome: 'Custo Mercadoria Vendida', tipo: 'producao', nivel: 2, areaCodigo: null },
  { codigo: '51101', nome: 'Custo da Mercadoria Vendida', tipo: 'producao', nivel: 3, areaCodigo: '511' },
];

export const PLANO_CONTAS_AGRICOLA = {
  pessoal: [
    { codigo: '71101001', nome: "SALARIOS", origem: 'Custo' },
    { codigo: '71101002', nome: "PREMIOS E GRATIFICACOES", origem: 'Custo' },
    { codigo: '71101003', nome: "HORAS EXTRAS", origem: 'Custo' },
    { codigo: '71101004', nome: "FERIAS E ABONO", origem: 'Custo' },
    { codigo: '71101005', nome: "13º SALARIO", origem: 'Custo' },
    { codigo: '71101006', nome: "INSS (GPS)", origem: 'Custo' },
    { codigo: '71101007', nome: "FGTS (GFIP)", origem: 'Custo' },
    { codigo: '71101008', nome: "INDENIZACOES E AVISO PREVIO", origem: 'Custo' },
    { codigo: '71101009', nome: "VALE ELETRONICO (VEM)", origem: 'Custo' },
    { codigo: '71101010', nome: "CESTAS BASICAS", origem: 'Custo' },
    { codigo: '71101011', nome: "FARDAMENTOS", origem: 'Custo' },
    { codigo: '71101012', nome: "ASSISTENCIA MEDICA E SOCIAL", origem: 'Custo' },
    { codigo: '71101013', nome: "DESPESAS COM TREINAMENTO DE PESSOAL", origem: 'Custo' },
    { codigo: '71101014', nome: "PENSAO ALIMENTICIA", origem: 'Custo' },
    { codigo: '71101015', nome: "SEGURANCA DO TRABALHO", origem: 'Custo' },
    { codigo: '71101016', nome: "CURSOS E TREINAMENTOS", origem: 'Custo' },
    { codigo: '71101017', nome: "TRANSPORTE DE PESSOAL", origem: 'Custo' },
    { codigo: '71101018', nome: "ALIMENTACAO", origem: 'Custo' },
    { codigo: '71101019', nome: "OUTRAS DESPESAS COM PESSOAL", origem: 'Custo' },
    { codigo: '71101020', nome: "EMPRESTIMOS A FUNCIONARIOS", origem: 'Custo' },
    { codigo: '71101021', nome: "RETIRADAS", origem: 'Custo' },
    { codigo: '71101022', nome: "INSALUBRIDADE", origem: 'Custo' },
    { codigo: '71101098', nome: "RATEIO - MAO DE OBRA", origem: 'Custo' },
    { codigo: '71102006', nome: "REFEITORIO", origem: 'Custo' },
    { codigo: '71102018', nome: "MATERIAL DE EPI", origem: 'Custo' },
    { codigo: '71102044', nome: "PRODUTOS DE ENFERMARIA", origem: 'Custo' },
    { codigo: '34101001', nome: "SALARIOS", origem: 'Despesa' },
    { codigo: '34101002', nome: "PREMIOS E GRATIFICACOES", origem: 'Despesa' },
    { codigo: '34101003', nome: "13º SALARIO", origem: 'Despesa' },
    { codigo: '34101004', nome: "FERIAS", origem: 'Despesa' },
    { codigo: '34101005', nome: "INSS (GPS)", origem: 'Despesa' },
    { codigo: '34101006', nome: "FGTS (GFIP)", origem: 'Despesa' },
    { codigo: '34101007', nome: "INDENIZACOES E AVISO PREVIO", origem: 'Despesa' },
    { codigo: '34101008', nome: "VALE ELETRONICO (VEM)", origem: 'Despesa' },
    { codigo: '34101009', nome: "CESTAS BASICAS", origem: 'Despesa' },
    { codigo: '34101010', nome: "FARDAMENTOS", origem: 'Despesa' },
    { codigo: '34101011', nome: "ASSISTENCIA MEDICA E SOCIAL", origem: 'Despesa' },
    { codigo: '34101012', nome: "TREINAMENTO DE PESSOAL", origem: 'Despesa' },
    { codigo: '34101014', nome: "HORAS EXTRAS", origem: 'Despesa' },
    { codigo: '34101015', nome: "ALIMENTACAO", origem: 'Despesa' },
    { codigo: '34201001', nome: "SALARIOS", origem: 'Despesa' },
    { codigo: '34201002', nome: "PREMIOS E GRATIFICACOES", origem: 'Despesa' },
    { codigo: '34201003', nome: "13º SALARIO", origem: 'Despesa' },
    { codigo: '34201004', nome: "FERIAS", origem: 'Despesa' },
    { codigo: '34201005', nome: "INSS (GPS)", origem: 'Despesa' },
    { codigo: '34201006', nome: "FGTS (GFIP)", origem: 'Despesa' },
    { codigo: '34201007', nome: "INDENIZACOES E AVISO PREVIO", origem: 'Despesa' },
    { codigo: '34201008', nome: "VALE ELETRONICO (VEM)", origem: 'Despesa' },
    { codigo: '34201009', nome: "CESTAS BASICAS", origem: 'Despesa' },
    { codigo: '34201010', nome: "FARDAMENTOS - EPI", origem: 'Despesa' },
    { codigo: '34201011', nome: "ASSISTENCIA MEDICA E SOCIAL", origem: 'Despesa' },
    { codigo: '34201012', nome: "DESPESA COM TREINAMENTO DE PESSOAL", origem: 'Despesa' },
    { codigo: '34201013', nome: "PENSAO ALIMENTICIA", origem: 'Despesa' },
    { codigo: '34201014', nome: "HORAS EXTRAS", origem: 'Despesa' },
    { codigo: '34201015', nome: "ALIMENTACAO", origem: 'Despesa' },
    { codigo: '34201019', nome: "OUTRAS DESP COM FUNCIONARIOS", origem: 'Despesa' },
    { codigo: '34201022', nome: "INSALUBRIDADE", origem: 'Despesa' },
    { codigo: '34202009', nome: "DESPESA  ALIMENTACAO", origem: 'Despesa' },
    { codigo: '34202013', nome: "DESPESAS COM FESTAS E COMEMORACOES", origem: 'Despesa' },
    { codigo: '34202021', nome: "REFEICOES", origem: 'Despesa' },
    { codigo: '34203001', nome: "PROLABORE", origem: 'Despesa' },
    { codigo: '34203002', nome: "INSS - PROLABORE", origem: 'Despesa' },
  ],
  administrativo_utilidades: [
    { codigo: '71102001', nome: "ENERGIA", origem: 'Custo' },
    { codigo: '71102002', nome: "TELEFONE - INTERNET", origem: 'Custo' },
    { codigo: '71102005', nome: "MATERIAL DE USO E CONSUMO", origem: 'Custo' },
    { codigo: '71102021', nome: "CAIXA FUNDO FIXO", origem: 'Custo' },
    { codigo: '71102024', nome: "MATERIAL DE EXPEDIENTE", origem: 'Custo' },
    { codigo: '71102035', nome: "DESPESAS COM SEGUROS", origem: 'Custo' },
    { codigo: '71102043', nome: "AGUA", origem: 'Custo' },
    { codigo: '71102045', nome: "MATERIAL ELETRICO", origem: 'Custo' },
    { codigo: '71102047', nome: "MATERIAL DIVERSOS", origem: 'Custo' },
    { codigo: '71102090', nome: "DIVERSOS", origem: 'Custo' },
    { codigo: '71102098', nome: "RATEIO - DESPESAS GERAIS", origem: 'Custo' },
    { codigo: '71102102', nome: "COPIAS E PLOTAGENS", origem: 'Custo' },
    { codigo: '71102104', nome: "SEGURO DE OBRAS", origem: 'Custo' },
    { codigo: '71104009', nome: "MATERIAL ELETRICO", origem: 'Custo' },
    { codigo: '34104009', nome: "MATERIAL DE EXPEDIENTE", origem: 'Despesa' },
    { codigo: '34104033', nome: "MATERIAIS DIVERSOS", origem: 'Despesa' },
    { codigo: '34202001', nome: "ENERGIA", origem: 'Despesa' },
    { codigo: '34202002', nome: "AGUA E ESGOTO", origem: 'Despesa' },
    { codigo: '34202003', nome: "TELEFONE - INTERNET", origem: 'Despesa' },
    { codigo: '34202005', nome: "CORREIOS E MALOTES", origem: 'Despesa' },
    { codigo: '34202006', nome: "MATERIAL DE EXPEDIENTE", origem: 'Despesa' },
    { codigo: '34202008', nome: "LIVROS, JORNAIS E REVISTAS", origem: 'Despesa' },
    { codigo: '34202012', nome: "BENS DE PEQUENO VALOR", origem: 'Despesa' },
    { codigo: '34202022', nome: "CAIXA FUNDO FIXO", origem: 'Despesa' },
    { codigo: '34202028', nome: "DESPESAS COM SEGUROS", origem: 'Despesa' },
    { codigo: '34202034', nome: "DESPESAS ADMINISTRATIVAS RATEADAS", origem: 'Despesa' },
    { codigo: '34202037', nome: "CERTIFICACOES", origem: 'Despesa' },
    { codigo: '34202090', nome: "DIVERSOS", origem: 'Despesa' },
    { codigo: '34202091', nome: "DESPESA COM CARTAO DE CREDITO", origem: 'Despesa' },
    { codigo: '34202093', nome: "MEDICAMENTO E FARMACIA", origem: 'Despesa' }, // Base orçamento 2026.xlsx 2026-08-24
  ],
  servicos: [
    { codigo: '71102003', nome: "SERVICOS DE TERCEIROS", origem: 'Custo' },
    { codigo: '71102016', nome: "ASSESSORIAS E CONSULTORIAS", origem: 'Custo' },
    { codigo: '71102017', nome: "SERVICO PRESTADO PESSOA FISICA", origem: 'Custo' },
    { codigo: '71102031', nome: "SEGURANCA E VIGILANCIA", origem: 'Custo' },
    { codigo: '71103001', nome: "SERVICOS TECNICOS", origem: 'Custo' }, // De/Para Camadas.xlsx 2026-08-20
    { codigo: '71103099', nome: "SERVICOS DIVERSOS", origem: 'Custo' }, // Base orçamento 2026.xlsx 2026-08-24
    { codigo: '71105002', nome: "CERTIFICADO DE QUALIDADE", origem: 'Custo' }, // Base orçamento 2026.xlsx 2026-08-24
    { codigo: '34104013', nome: "SERVICOS PRESTADOS PESSOA JURIDICA", origem: 'Despesa' },
    { codigo: '34104019', nome: "SERVICO PRESTADO PESSOA FISICA", origem: 'Despesa' },
    { codigo: '34202010', nome: "SERVICOS DE TERCEIROS - PESSSOA JURIDICA", origem: 'Despesa' },
    { codigo: '34202017', nome: "SERVICOS DE TERCEIRO PESSOA FISICA", origem: 'Despesa' },
    { codigo: '34202023', nome: "SEGURANCA E VIGILANCIA", origem: 'Despesa' },
  ],
  manutencao: [
    { codigo: '71102004', nome: "MANUTENCAO, CONSERVACAO E LIMPEZA", origem: 'Custo' },
    { codigo: '71102033', nome: "MATERIAL DE MANUT - VEICULOS-MOTOS", origem: 'Custo' },
    { codigo: '71102034', nome: "PECAS E SERV - TRATORES-IMPLEMENTOS", origem: 'Custo' }, // De/Para Camadas.xlsx 2026-08-20
    { codigo: '71102036', nome: "MANUTENCAO DA COMUNICACAO", origem: 'Custo' }, // De/Para Camadas.xlsx 2026-08-20
    { codigo: '71102046', nome: "MATERIAL DE OFICINA", origem: 'Custo' },
    { codigo: '71102050', nome: "PECAS E SERV", origem: 'Custo' }, // Base orçamento 2026.xlsx 2026-08-24
    { codigo: '71102103', nome: "MANUTENCAO DE EQUIPAMENTOS MECANICOS", origem: 'Custo' },
    { codigo: '34104002', nome: "MANUTENCAO DE VEICULOS", origem: 'Despesa' },
    { codigo: '34104010', nome: "MATERIAL DE MANUTENCAO", origem: 'Despesa' },
    { codigo: '34202004', nome: "MANUTENCAO DE VEICULOS", origem: 'Despesa' },
    { codigo: '34202007', nome: "MANUTENCAO, CONSERVACAO E LIMPEZA", origem: 'Despesa' },
    { codigo: '34202026', nome: "MANUTENCAO DE MAQ E EQUIPAMENTOS", origem: 'Despesa' },
  ],
  impostos: [
    { codigo: '71102007', nome: "IPVA - IMPOSTOS E TAXAS", origem: 'Custo' },
    { codigo: '34202014', nome: "IPVA - IMPOSTOS E TAXAS", origem: 'Despesa' },
    { codigo: '34202016', nome: "CONTRIBUICAO SINDICAL", origem: 'Despesa' },
    { codigo: '34202036', nome: "ROYALTIES", origem: 'Despesa' },
  ],
  depreciacao: [
    { codigo: '71102008', nome: "ENCARGOS COM DEPRECIACAO", origem: 'Custo' },
    { codigo: '34202011', nome: "ENCARGOS COM DEPRECIACAO", origem: 'Despesa' },
    { codigo: '34202020', nome: "PIS - COFINS SOBRE A DEPRECIACAO", origem: 'Despesa' },
  ],
  fretes: [
    { codigo: '71102009', nome: "FRETES E CARRETOS", origem: 'Custo' },
    { codigo: '71102012', nome: "COMBUSTIVEIS E LUBRIFICANTES", origem: 'Custo' },
    { codigo: '71102038', nome: "LOGISTICA EXPORTACAO", origem: 'Custo' },
    { codigo: '71102039', nome: "LOGISTICA IMPORTACAO", origem: 'Custo' },
    { codigo: '34104001', nome: "FRETES E CARRETOS", origem: 'Despesa' },
    { codigo: '34104003', nome: "SERVICOS ADUANEIROS", origem: 'Despesa' },
    { codigo: '34104004', nome: "DESPACHANTE", origem: 'Despesa' },
    { codigo: '34104031', nome: "COMBUSTIVEIS E LUBRIFICANTES", origem: 'Despesa' },
    { codigo: '34202015', nome: "FRETES E CARRETOS", origem: 'Despesa' },
    { codigo: '34202029', nome: "DESPESAS COM COMBUSTIVEL", origem: 'Despesa' },
  ],
  producao: [
    { codigo: '71102010', nome: "MATERIA PRIMA", origem: 'Custo' },
    { codigo: '71102011', nome: "METERIA ORGANICA", origem: 'Custo' },
    { codigo: '71102013', nome: "MATERIAL DE EMBALAGEM", origem: 'Custo' },
    { codigo: '71102014', nome: "FERTILIZANTES", origem: 'Custo' },
    { codigo: '71102015', nome: "DEFENSIVOS", origem: 'Custo' },
    { codigo: '71102019', nome: "FERRAMENTAS DE PRODUCAO", origem: 'Custo' },
    { codigo: '71102022', nome: "MATERIAL DE CONSTRUCAO", origem: 'Custo' },
    { codigo: '71102037', nome: "ANALISES LABORATORIAIS", origem: 'Custo' },
    { codigo: '71102040', nome: "MONITORAMENTO DE PRAGAS", origem: 'Custo' },
    { codigo: '71102042', nome: "DESPESAS COM AQUISICOES DE UVA", origem: 'Custo' },
    { codigo: '71102048', nome: "MATERIAL PARA MANUT DE PARREIRA", origem: 'Custo' },
    { codigo: '71102049', nome: "MATERIAL DE IRRIGACAO", origem: 'Custo' }, // De/Para Camadas.xlsx 2026-08-20
    { codigo: '71102095', nome: "RATEIO - PACKING HOUSE", origem: 'Custo' },
    { codigo: '71102096', nome: "RATEIO - INDIRETO FAZENDA", origem: 'Custo' },
    { codigo: '71102097', nome: "RATEIO DA PRODUCAO", origem: 'Custo' },
    { codigo: '34202030', nome: "MATERIAL DE CONSTRUCAO", origem: 'Despesa' },
  ],
  comercial: [
    { codigo: '71102020', nome: "STAND DE VENDAS", origem: 'Custo' },
    { codigo: '34102001', nome: "COMISSOES", origem: 'Despesa' },
    { codigo: '34103001', nome: "DESPESAS COM MARKETING", origem: 'Despesa' },
    { codigo: '34202035', nome: "BRINDES E DONATIVOS", origem: 'Despesa' },
  ],
  viagens: [
    { codigo: '71102026', nome: "DESPESAS COM VIAGENS", origem: 'Custo' },
    { codigo: '34202018', nome: "DESPESAS COM VIAGENS", origem: 'Despesa' },
  ],
  locacao: [
    { codigo: '71102032', nome: "LOCACAO DE MAQUINAS E EQUIPAMENTOS", origem: 'Custo' },
    { codigo: '34202019', nome: "ALUGUEL A PESSOA FISICA", origem: 'Despesa' },
    { codigo: '34202025', nome: "LOCACAO DE MAQ E EQUIPAMENTOS", origem: 'Despesa' },
    { codigo: '34202033', nome: "CONDOMINIOS DE IMOVEIS PROPRIOS", origem: 'Despesa' },
  ],
  tecnologia: [
    { codigo: '34202027', nome: "CONSULTORIAS DE SISTEMAS", origem: 'Despesa' },
    { codigo: '34202031', nome: "MATERIAL DE TI E COMUNICACAO", origem: 'Despesa' },
  ],
};

// CCs reais da ARA Resorts (Centros de Custos - ARA Resorts 1.xlsx,
// 2026-08-20) — 12 áreas (nivel:2) e seus CCs analíticos (nivel:3).
// `resorts: ['beach'|'villa']` indica em qual(is) resort(s) o CC existe —
// a maioria nos dois, mas "AT Ampliação Beach" só no Beach, "Villa Muro
// Alto"/"AT Ampliação Villa" só na Villa. Sem De/Para de conta × CC pro
// Resorts (diferente da Agrícola) — todo CC analítico recebe o plano de
// contas completo (PLANO_CONTAS_RESORTS, sem alteração), mesmo critério do
// Corporativo. Espelho exato de CCS_RESORTS em frontend/src/OrcamentoARA.jsx.
export const CCS_RESORTS = [
  { codigo: '00', nome: 'Diretoria', tipo: 'despesa', nivel: 2, areaCodigo: null, resorts: ['beach', 'villa'] },
  { codigo: '0002', nome: 'Conselho', tipo: 'despesa', nivel: 3, areaCodigo: '00', resorts: ['beach', 'villa'] },

  { codigo: '01', nome: 'Hospedagem', tipo: 'producao', nivel: 2, areaCodigo: null, resorts: ['beach', 'villa'] },
  { codigo: '0101', nome: 'Apartamentos', tipo: 'producao', nivel: 3, areaCodigo: '01', resorts: ['beach', 'villa'] },
  { codigo: '0102', nome: 'Recepção', tipo: 'producao', nivel: 3, areaCodigo: '01', resorts: ['beach', 'villa'] },
  { codigo: '0103', nome: 'Reservas', tipo: 'producao', nivel: 3, areaCodigo: '01', resorts: ['beach', 'villa'] },
  { codigo: '0105', nome: 'Esporte e Lazer', tipo: 'producao', nivel: 3, areaCodigo: '01', resorts: ['beach', 'villa'] },
  { codigo: '0106', nome: 'Governança', tipo: 'producao', nivel: 3, areaCodigo: '01', resorts: ['beach', 'villa'] },
  { codigo: '0107', nome: 'Experiências', tipo: 'producao', nivel: 3, areaCodigo: '01', resorts: ['beach', 'villa'] },

  { codigo: '02', nome: 'Alimentos e Bebidas', tipo: 'producao', nivel: 2, areaCodigo: null, resorts: ['beach', 'villa'] },
  { codigo: '0201', nome: 'Restaurante', tipo: 'producao', nivel: 3, areaCodigo: '02', resorts: ['beach', 'villa'] },
  { codigo: '0202', nome: 'Room Service', tipo: 'producao', nivel: 3, areaCodigo: '02', resorts: ['beach', 'villa'] },
  { codigo: '0203', nome: 'Cozinha', tipo: 'producao', nivel: 3, areaCodigo: '02', resorts: ['beach', 'villa'] },
  { codigo: '0204', nome: 'Frigobar', tipo: 'producao', nivel: 3, areaCodigo: '02', resorts: ['beach', 'villa'] },
  { codigo: '0205', nome: 'Café da Manhã', tipo: 'producao', nivel: 3, areaCodigo: '02', resorts: ['beach', 'villa'] },
  { codigo: '0206', nome: 'Refeitório', tipo: 'producao', nivel: 3, areaCodigo: '02', resorts: ['beach', 'villa'] },
  { codigo: '0207', nome: 'Bar Piscina', tipo: 'producao', nivel: 3, areaCodigo: '02', resorts: ['beach', 'villa'] },
  { codigo: '0208', nome: 'Bar Praia', tipo: 'producao', nivel: 3, areaCodigo: '02', resorts: ['beach', 'villa'] },
  { codigo: '0209', nome: 'Eventos A&B', tipo: 'producao', nivel: 3, areaCodigo: '02', resorts: ['beach', 'villa'] },
  { codigo: '0210', nome: 'Produção de Alimentos', tipo: 'producao', nivel: 3, areaCodigo: '02', resorts: ['beach', 'villa'] },
  { codigo: '0212', nome: 'Padaria', tipo: 'producao', nivel: 3, areaCodigo: '02', resorts: ['beach', 'villa'] },
  { codigo: '0213', nome: 'Confeitaria', tipo: 'producao', nivel: 3, areaCodigo: '02', resorts: ['beach', 'villa'] },
  { codigo: '0214', nome: 'Deck Praia', tipo: 'producao', nivel: 3, areaCodigo: '02', resorts: ['beach', 'villa'] },
  { codigo: '0215', nome: 'Praia Polinésia', tipo: 'producao', nivel: 3, areaCodigo: '02', resorts: ['beach', 'villa'] },
  { codigo: '0216', nome: 'Piscina Polinésia', tipo: 'producao', nivel: 3, areaCodigo: '02', resorts: ['beach', 'villa'] },
  { codigo: '0217', nome: 'Lobby Bar', tipo: 'producao', nivel: 3, areaCodigo: '02', resorts: ['villa'] },

  { codigo: '03', nome: 'Administração', tipo: 'despesa', nivel: 2, areaCodigo: null, resorts: ['beach', 'villa'] },
  { codigo: '0301', nome: 'Diretoria', tipo: 'despesa', nivel: 3, areaCodigo: '03', resorts: ['beach', 'villa'] },
  { codigo: '0302', nome: 'Apoio Administrativo', tipo: 'despesa', nivel: 3, areaCodigo: '03', resorts: ['beach', 'villa'] },
  { codigo: '0303', nome: 'Almoxarifado', tipo: 'despesa', nivel: 3, areaCodigo: '03', resorts: ['beach', 'villa'] },
  { codigo: '0304', nome: 'RH/Departamento Pessoal', tipo: 'despesa', nivel: 3, areaCodigo: '03', resorts: ['beach', 'villa'] },
  { codigo: '0306', nome: 'Financeiro', tipo: 'despesa', nivel: 3, areaCodigo: '03', resorts: ['beach', 'villa'] },
  { codigo: '0307', nome: 'Compras', tipo: 'despesa', nivel: 3, areaCodigo: '03', resorts: ['beach', 'villa'] },
  { codigo: '0308', nome: 'Tecnologia da Informação', tipo: 'despesa', nivel: 3, areaCodigo: '03', resorts: ['beach', 'villa'] },
  { codigo: '0310', nome: 'Portaria/Segurança', tipo: 'despesa', nivel: 3, areaCodigo: '03', resorts: ['beach', 'villa'] },

  { codigo: '04', nome: 'Serviços', tipo: 'despesa', nivel: 2, areaCodigo: null, resorts: ['beach', 'villa'] },
  { codigo: '0402', nome: 'Lavanderia', tipo: 'despesa', nivel: 3, areaCodigo: '04', resorts: ['beach', 'villa'] },

  { codigo: '05', nome: 'Comercial', tipo: 'despesa', nivel: 2, areaCodigo: null, resorts: ['beach', 'villa'] },
  { codigo: '0502', nome: 'Propaganda e Marketing', tipo: 'despesa', nivel: 3, areaCodigo: '05', resorts: ['beach', 'villa'] },

  { codigo: '06', nome: 'Manutenção', tipo: 'despesa', nivel: 2, areaCodigo: null, resorts: ['beach', 'villa'] },
  { codigo: '0601', nome: 'Manutenção Predial Adm', tipo: 'despesa', nivel: 3, areaCodigo: '06', resorts: ['beach', 'villa'] },
  { codigo: '0602', nome: 'Obras e Reformas', tipo: 'despesa', nivel: 3, areaCodigo: '06', resorts: ['beach', 'villa'] },

  { codigo: '94', nome: 'AT Ampliação Beach', tipo: 'despesa', nivel: 2, areaCodigo: null, resorts: ['beach'] },
  { codigo: '9401', nome: 'Ampliação Construção', tipo: 'despesa', nivel: 3, areaCodigo: '94', resorts: ['beach'] },
  { codigo: '9402', nome: 'Ampliação Montagem', tipo: 'despesa', nivel: 3, areaCodigo: '94', resorts: ['beach'] },

  { codigo: '95', nome: 'Villa Muro Alto', tipo: 'producao', nivel: 2, areaCodigo: null, resorts: ['villa'] },
  { codigo: '9501', nome: 'Operação Villa Muro Alto', tipo: 'producao', nivel: 3, areaCodigo: '95', resorts: ['villa'] },

  { codigo: '96', nome: 'AT Ampliação Villa', tipo: 'despesa', nivel: 2, areaCodigo: null, resorts: ['villa'] },
  { codigo: '9601', nome: 'Ampliação Construção', tipo: 'despesa', nivel: 3, areaCodigo: '96', resorts: ['villa'] },
  { codigo: '9602', nome: 'Ampliação Montagem', tipo: 'despesa', nivel: 3, areaCodigo: '96', resorts: ['villa'] },

  { codigo: '97', nome: 'Condomínio Polinésia', tipo: 'despesa', nivel: 2, areaCodigo: null, resorts: ['beach', 'villa'] },
  { codigo: '9701', nome: 'Condomínio Polinésia', tipo: 'despesa', nivel: 3, areaCodigo: '97', resorts: ['beach', 'villa'] },
  { codigo: '9702', nome: 'La Fleur Collection', tipo: 'despesa', nivel: 3, areaCodigo: '97', resorts: ['beach', 'villa'] },

  { codigo: '99', nome: 'Bloco 3', tipo: 'despesa', nivel: 2, areaCodigo: null, resorts: ['beach', 'villa'] },
  { codigo: '9901', nome: 'Bloco 3', tipo: 'despesa', nivel: 3, areaCodigo: '99', resorts: ['beach', 'villa'] },
];

// Resorts_Contas_x_Pacote: 260 contas classificadas (OK), 16 fora do escopo (CAPEX/obra, conta sintética, despesa financeira, ou sem pacote) — excluídas

export const PACOTES_RESORTS = [
  { id: 'producao', nome: "Produção", ref: 'Matriz_Governanca_OBZ_2027_4 (6 contas)' },
  { id: 'pessoal', nome: "Pessoal", ref: 'Matriz_Governanca_OBZ_2027_4 (83 contas)' },
  { id: 'administrativo_utilidades', nome: "Administrativo e Utilidades", ref: 'Matriz_Governanca_OBZ_2027_4 (54 contas)' },
  { id: 'tecnologia', nome: "Tecnologia e Inovação", ref: 'Matriz_Governanca_OBZ_2027_4 (2 contas)' },
  { id: 'comercial', nome: "Comercial e Marketing", ref: 'Matriz_Governanca_OBZ_2027_4 (9 contas)' },
  { id: 'manutencao', nome: "Manutenção", ref: 'Matriz_Governanca_OBZ_2027_4 (25 contas)' },
  { id: 'fretes', nome: "Fretes e Logística", ref: 'Matriz_Governanca_OBZ_2027_4 (16 contas)' },
  { id: 'servicos', nome: "Serviços de Terceiros", ref: 'Matriz_Governanca_OBZ_2027_4 (22 contas)' },
  { id: 'locacao', nome: "Locação e Ocupação", ref: 'Matriz_Governanca_OBZ_2027_4 (14 contas)' },
  { id: 'impostos', nome: "Impostos Indiretos e Diretos", ref: 'Matriz_Governanca_OBZ_2027_4 (12 contas)' },
  { id: 'viagens', nome: "Viagens", ref: 'Matriz_Governanca_OBZ_2027_4 (6 contas)' },
  { id: 'depreciacao', nome: "Depreciação e Amortização", ref: 'Matriz_Governanca_OBZ_2027_4 (11 contas)' },
];

export const PLANO_CONTAS_RESORTS = {
  producao: [
    { codigo: '410101010', nome: "ALIMENTOS", origem: 'Custo' },
    { codigo: '410101020', nome: "BEBIDAS", origem: 'Custo' },
    { codigo: '71102010', nome: "MATERIA PRIMA FIO", origem: 'Custo' },
    { codigo: '71102011', nome: "MATERIA PRIMA PRODUTOS QUIMICOS", origem: 'Custo' },
    { codigo: '71102099', nome: "RATEIO PARA MALHARIA", origem: 'Custo' },
    { codigo: '71102100', nome: "RATEIO PARA BENEFICIAMENTO", origem: 'Custo' },
  ],
  pessoal: [
    { codigo: '410201010', nome: "SALARIOS", origem: 'Custo' },
    { codigo: '410201020', nome: "PRO-LABORE", origem: 'Custo' },
    { codigo: '410201030', nome: "HORAS EXTRAS", origem: 'Custo' },
    { codigo: '410201035', nome: "INSS (GPS)", origem: 'Custo' },
    { codigo: '410201040', nome: "INDENIZACOES TRABALHISTAS", origem: 'Custo' },
    { codigo: '410201045', nome: "FGTS (SEFIP)", origem: 'Custo' },
    { codigo: '410201050', nome: "FERIAS", origem: 'Custo' },
    { codigo: '410201060', nome: "13º SALARIO", origem: 'Custo' },
    { codigo: '410201070', nome: "PENSAO ALIMENTICIA", origem: 'Custo' },
    { codigo: '410201080', nome: "QUINQUENIO", origem: 'Custo' },
    { codigo: '410201090', nome: "ACORDOS TRABALHISTAS", origem: 'Custo' },
    { codigo: '410201100', nome: "RECISOES", origem: 'Custo' },
    { codigo: '410201110', nome: "GRATIFICACOES", origem: 'Custo' },
    { codigo: '410201120', nome: "EXAMES MEDICOS", origem: 'Custo' },
    { codigo: '410201130', nome: "BOLSA-ESTAGIO", origem: 'Custo' },
    { codigo: '410201140', nome: "TRANSPORTE DE PESSOAL", origem: 'Custo' },
    { codigo: '410202010', nome: "CONVENIO MEDICO", origem: 'Custo' },
    { codigo: '410202020', nome: "CONVENIO ODONTOLOGICO", origem: 'Custo' },
    { codigo: '410202030', nome: "CESTA BASICA", origem: 'Custo' },
    { codigo: '410203010', nome: "CLIMA ORGANIZACIONAL (RH)", origem: 'Custo' },
    { codigo: '410301110', nome: "EPI", origem: 'Custo' },
    { codigo: '410307080', nome: "LANCHES E REFEICOES", origem: 'Custo' },
    { codigo: '410307090', nome: "MEDICAMENTOS", origem: 'Custo' },
    { codigo: '410307190', nome: "CURSOS/SEMINARIOS", origem: 'Custo' },
    { codigo: '410307250', nome: "UNIFORMES", origem: 'Custo' },
    { codigo: '71101001', nome: "SALARIOS E ORDENADOS", origem: 'Custo' },
    { codigo: '71101002', nome: "PREMIOS E GRATIFICACOES", origem: 'Custo' },
    { codigo: '71101003', nome: "HORAS EXTRAS", origem: 'Custo' },
    { codigo: '71101004', nome: "FERIAS E ABONO", origem: 'Custo' },
    { codigo: '71101005', nome: "13º SALARIO", origem: 'Custo' },
    { codigo: '71101006', nome: "INSS (GPS)", origem: 'Custo' },
    { codigo: '71101007', nome: "FGTS (GFIP)", origem: 'Custo' },
    { codigo: '71101008', nome: "INDENIZACOES E AVISO PREVIO", origem: 'Custo' },
    { codigo: '71101009', nome: "VALE ELETRONICO (VEM)", origem: 'Custo' },
    { codigo: '71101010', nome: "CESTAS BASICAS", origem: 'Custo' },
    { codigo: '71101011', nome: "FARDAMENTOS", origem: 'Custo' },
    { codigo: '71101012', nome: "ASSISTENCIA MEDICA E SOCIAL", origem: 'Custo' },
    { codigo: '71101013', nome: "DESPESAS COM TREINAMENTO DE PESSOAL", origem: 'Custo' },
    { codigo: '71101014', nome: "PENSAO ALIMENTICIA", origem: 'Custo' },
    { codigo: '71101018', nome: "ALIMENTACAO", origem: 'Custo' },
    { codigo: '71102006', nome: "REFEICOES", origem: 'Custo' },
    { codigo: '71102036', nome: "DESPESAS COM FESTAS E BRINDES", origem: 'Custo' },
    { codigo: '34101001', nome: "ORDENADOS E SALARIOS", origem: 'Despesa' },
    { codigo: '34101002', nome: "PREMIOS E GRATIFICACOES", origem: 'Despesa' },
    { codigo: '34101003', nome: "13º SALARIO", origem: 'Despesa' },
    { codigo: '34101004', nome: "FERIAS", origem: 'Despesa' },
    { codigo: '34101005', nome: "INSS (GPS)", origem: 'Despesa' },
    { codigo: '34101006', nome: "FGTS (GFIP)", origem: 'Despesa' },
    { codigo: '34101007', nome: "INDENIZACOES E AVISO PREVIO", origem: 'Despesa' },
    { codigo: '34101008', nome: "VALE ELETRONICO (VEM)", origem: 'Despesa' },
    { codigo: '34101009', nome: "CESTAS BASICAS", origem: 'Despesa' },
    { codigo: '34101010', nome: "FARDAMENTOS", origem: 'Despesa' },
    { codigo: '34101011', nome: "ASSISTENCIA MEDICA E SOCIAL", origem: 'Despesa' },
    { codigo: '34101012', nome: "DESPESAS COM TREINAMENTO DE PESSOAL", origem: 'Despesa' },
    { codigo: '34101014', nome: "HORAS EXTRAS", origem: 'Despesa' },
    { codigo: '34101015', nome: "ALIMENTACAO", origem: 'Despesa' },
    { codigo: '34104012', nome: "DESPESAS COM ALIMENTACAO", origem: 'Despesa' },
    { codigo: '34104016', nome: "DESPESAS COM FESTAS E BRINDES", origem: 'Despesa' },
    { codigo: '34104023', nome: "REFEICOES", origem: 'Despesa' },
    { codigo: '34201001', nome: "ORDENADOS E SALARIOS", origem: 'Despesa' },
    { codigo: '34201002', nome: "PREMIOS E GRATIFICACOES", origem: 'Despesa' },
    { codigo: '34201003', nome: "13º SALARIO", origem: 'Despesa' },
    { codigo: '34201004', nome: "FERIAS", origem: 'Despesa' },
    { codigo: '34201005', nome: "INSS (GPS)", origem: 'Despesa' },
    { codigo: '34201006', nome: "FGTS (GFIP)", origem: 'Despesa' },
    { codigo: '34201007', nome: "INDENIZACOES E AVISO PREVIO", origem: 'Despesa' },
    { codigo: '34201008', nome: "VALE ELETRONICO (VEM)", origem: 'Despesa' },
    { codigo: '34201009', nome: "CESTAS BASICAS", origem: 'Despesa' },
    { codigo: '34201010', nome: "FARDAMENTOS", origem: 'Despesa' },
    { codigo: '34201011', nome: "ASSISTENCIA MEDICA E SOCIAL", origem: 'Despesa' },
    { codigo: '34201012', nome: "DESPESA COM TREINAMENTO DE PESSOAL", origem: 'Despesa' },
    { codigo: '34201013', nome: "PENSAO ALIMENTICIA", origem: 'Despesa' },
    { codigo: '34201014', nome: "PRO-LABORE", origem: 'Despesa' },
    { codigo: '34201015', nome: "HORAS EXTRAS", origem: 'Despesa' },
    { codigo: '34201016', nome: "ALIMENTACAO", origem: 'Despesa' },
    { codigo: '34201017', nome: "SEGURANCA DO TRABALHO", origem: 'Despesa' },
    { codigo: '34201019', nome: "OUTRAS DESPESAS COM FUNCIONARIOS", origem: 'Despesa' },
    { codigo: '34201022', nome: "INSALUBRIDADE", origem: 'Despesa' },
    { codigo: '34202009', nome: "DESPESA  ALIMENTACAO", origem: 'Despesa' },
    { codigo: '34202013', nome: "DESPESAS COM FESTAS E BRINDES", origem: 'Despesa' },
    { codigo: '34202021', nome: "REFEICOES", origem: 'Despesa' },
    { codigo: '34203001', nome: "PRO LABORE", origem: 'Despesa' },
    { codigo: '34203002', nome: "PRO LABORE", origem: 'Despesa' },
  ],
  administrativo_utilidades: [
    { codigo: '410301010', nome: "MATERIAL DE ESCRITORIO", origem: 'Custo' },
    { codigo: '410301030', nome: "MATERIAL DE LIMPEZA", origem: 'Custo' },
    { codigo: '410301050', nome: "MATERIAL DE LAVANDERIA", origem: 'Custo' },
    { codigo: '410301060', nome: "MATERIAL DE HOSPEDAGEM", origem: 'Custo' },
    { codigo: '410301080', nome: "ALMOXARIFADO", origem: 'Custo' },
    { codigo: '410301090', nome: "MATERIAL DESCARTAVEL", origem: 'Custo' },
    { codigo: '410301100', nome: "MATERIAL DE EXPERIENCIA", origem: 'Custo' },
    { codigo: '410301120', nome: "UTENSILIOS", origem: 'Custo' },
    { codigo: '410301220', nome: "ENXOVAIS", origem: 'Custo' },
    { codigo: '410303010', nome: "AGUA E ESGOTO", origem: 'Custo' },
    { codigo: '410303020', nome: "ENERGIA ELETRICA", origem: 'Custo' },
    { codigo: '410303030', nome: "GAS", origem: 'Custo' },
    { codigo: '410303040', nome: "TELEFONIA", origem: 'Custo' },
    { codigo: '410304060', nome: "SEGUROS DE VEICULOS", origem: 'Custo' },
    { codigo: '410307040', nome: "CORREIOS E MALOTES", origem: 'Custo' },
    { codigo: '410307110', nome: "INTERNET", origem: 'Custo' },
    { codigo: '410307210', nome: "SEGURO", origem: 'Custo' },
    { codigo: '410307270', nome: "CAIXA FUNDO FIXO", origem: 'Custo' },
    { codigo: '410307280', nome: "DIVERSOS", origem: 'Custo' },
    { codigo: '410307300', nome: "DESPESAS ADMINISTRATIVAS RATEADA", origem: 'Custo' },
    { codigo: '410307310', nome: "BENS DE PEQUENO VALOR", origem: 'Custo' },
    { codigo: '410307320', nome: "REEMBOLSO DIVERSOS", origem: 'Custo' },
    { codigo: '71102001', nome: "ENERGIA ELETRICA", origem: 'Custo' },
    { codigo: '71102002', nome: "TELEFONE", origem: 'Custo' },
    { codigo: '71102005', nome: "MATERIAL DE USO E CONSUMO", origem: 'Custo' },
    { codigo: '71102021', nome: "CAIXA FUNDO FIXO", origem: 'Custo' },
    { codigo: '71102024', nome: "MATERIAL DE EXPEDIENTE", origem: 'Custo' },
    { codigo: '71102025', nome: "BENS DE PEQUENO VALOR", origem: 'Custo' },
    { codigo: '71102028', nome: "LIVROS JORNAIS E REVISTAS", origem: 'Custo' },
    { codigo: '71102029', nome: "CORREIOS E MALOTES", origem: 'Custo' },
    { codigo: '71102035', nome: "DESPESAS COM SEGUROS", origem: 'Custo' },
    { codigo: '34104005', nome: "ENERGIA ELETRICA", origem: 'Despesa' },
    { codigo: '34104006', nome: "AGUA E ESGOTO", origem: 'Despesa' },
    { codigo: '34104007', nome: "TELEFONE E INTERNET", origem: 'Despesa' },
    { codigo: '34104008', nome: "CORREIOS E MALOTES", origem: 'Despesa' },
    { codigo: '34104009', nome: "MATERIAL DE EXPEDIENTE", origem: 'Despesa' },
    { codigo: '34104011', nome: "LIVROS - JORNAIS E REVISTAS", origem: 'Despesa' },
    { codigo: '34104015', nome: "BENS DE PEQUENO VALOR", origem: 'Despesa' },
    { codigo: '34104024', nome: "CAIXA FUNDO FIXO", origem: 'Despesa' },
    { codigo: '34104030', nome: "DESPESAS COM SEGUROS", origem: 'Despesa' },
    { codigo: '34104033', nome: "MATERIAL DE USO E CONSUMO", origem: 'Despesa' },
    { codigo: '34104090', nome: "DIVERSOS", origem: 'Despesa' },
    { codigo: '34202001', nome: "ENERGIA ELETRICA", origem: 'Despesa' },
    { codigo: '34202002', nome: "AGUA E ESGOTO", origem: 'Despesa' },
    { codigo: '34202003', nome: "TELEFONE E INTERNET", origem: 'Despesa' },
    { codigo: '34202005', nome: "CORREIOS E MALOTES", origem: 'Despesa' },
    { codigo: '34202006', nome: "MATERIAL DE EXPEDIENTE", origem: 'Despesa' },
    { codigo: '34202008', nome: "LIVROS, JORNAIS E REVISTAS", origem: 'Despesa' },
    { codigo: '34202012', nome: "BENS DE PEQUENO VALOR", origem: 'Despesa' },
    { codigo: '34202022', nome: "CAIXA FUNDO FIXO", origem: 'Despesa' },
    { codigo: '34202028', nome: "DESPESAS COM SEGUROS", origem: 'Despesa' },
    { codigo: '34202031', nome: "MATERIAL DE USO E CONSUMO", origem: 'Despesa' },
    { codigo: '34202034', nome: "DESPESAS ADMINISTRATIVAS RATEADAS", origem: 'Despesa' },
    { codigo: '34202090', nome: "DIVERSOS", origem: 'Despesa' },
  ],
  tecnologia: [
    { codigo: '410301020', nome: "MATERIAL DE INFORMATICA", origem: 'Custo' },
    { codigo: '410307130', nome: "MANUTENCAO DE SOFTWARE", origem: 'Custo' },
  ],
  comercial: [
    { codigo: '410301040', nome: "MATERIAL DE PROMOCAO E PUBLICIDADE", origem: 'Custo' },
    { codigo: '410305050', nome: "PROPAGANDA E PUBLICIDADE", origem: 'Custo' },
    { codigo: '410306010', nome: "COMISSAO DE CARTAO DE CREDITO", origem: 'Custo' },
    { codigo: '410306020', nome: "COMISSAO DE AGENTES", origem: 'Custo' },
    { codigo: '410307140', nome: "BRINDES E PROMOCOES", origem: 'Custo' },
    { codigo: '410307150', nome: "DECORACAO", origem: 'Custo' },
    { codigo: '34102001', nome: "COMISSOES", origem: 'Despesa' },
    { codigo: '34103001', nome: "PROPAGANDA E PUBLICIDADE", origem: 'Despesa' },
    { codigo: '34202035', nome: "DOACOES", origem: 'Despesa' },
  ],
  manutencao: [
    { codigo: '410301070', nome: "MATERIAL DE MANUT./CONSERV.", origem: 'Custo' },
    { codigo: '410301130', nome: "MATERIAL MANUTENCAO ELETRICA", origem: 'Custo' },
    { codigo: '410301140', nome: "MATERIAL MANUTENCAO HIDRAULICA", origem: 'Custo' },
    { codigo: '410301150', nome: "MANUTENCAO LAMPADAS E REFRIGERACAO", origem: 'Custo' },
    { codigo: '410301160', nome: "MANUTENCAO CAMARAS E REFRIGERACAO", origem: 'Custo' },
    { codigo: '410301170', nome: "MANUTENCAO PISCINA", origem: 'Custo' },
    { codigo: '410301180', nome: "MANUTENCAO JARDIM", origem: 'Custo' },
    { codigo: '410301190', nome: "MANUTENCAO LAVANDERIA", origem: 'Custo' },
    { codigo: '410301200', nome: "MANUTENCAO EQUIPAMENTOS", origem: 'Custo' },
    { codigo: '410301210', nome: "MANUTENCAO PINTURA", origem: 'Custo' },
    { codigo: '410304010', nome: "MANUTENCAO DE VEICULOS", origem: 'Custo' },
    { codigo: '410307160', nome: "DEDETIZACAO", origem: 'Custo' },
    { codigo: '410307200', nome: "JARDINAGEM", origem: 'Custo' },
    { codigo: '410307230', nome: "ASSIST. TECNICA/REPAROS", origem: 'Custo' },
    { codigo: '71102004', nome: "MANUTENCAO, CONSERVACAO E LIMPEZA", origem: 'Custo' },
    { codigo: '71102022', nome: "MANUTENCAO PREDIAL", origem: 'Custo' },
    { codigo: '71102033', nome: "MANUTENCAO DE MAQ E EQUIPAMENTOS", origem: 'Custo' },
    { codigo: '34104002', nome: "MANUTENCAO DE VEICULOS", origem: 'Despesa' },
    { codigo: '34104010', nome: "MANUTENCAO - CONSERVACAO E LIMPEZA", origem: 'Despesa' },
    { codigo: '34104028', nome: "MANUTENCAO DE MAQUINAS E EQUIPAMENTOS", origem: 'Despesa' },
    { codigo: '34104032', nome: "MANUTENCAO PREDIAL", origem: 'Despesa' },
    { codigo: '34202004', nome: "MANUTENCAO DE VEICULOS", origem: 'Despesa' },
    { codigo: '34202007', nome: "CONSERVACAO E LIMPEZA", origem: 'Despesa' },
    { codigo: '34202026', nome: "MANUTENCAO DE MAQ E EQUIPAMENTOS", origem: 'Despesa' },
    { codigo: '34202030', nome: "MANUTENCAO PREDIAL", origem: 'Despesa' },
  ],
  fretes: [
    { codigo: '410301230', nome: "COMBUSTIVEIS E LUBRIFICANTES", origem: 'Custo' },
    { codigo: '410304020', nome: "DESPESAS COM COMBUSTIVEL", origem: 'Custo' },
    { codigo: '410304040', nome: "MULTAS DE TRANSITO", origem: 'Custo' },
    { codigo: '410304050', nome: "ESTACIONAMENTO E PEDAGIO", origem: 'Custo' },
    { codigo: '410307060', nome: "FRETES E CARRETOS", origem: 'Custo' },
    { codigo: '410307070', nome: "TRANSPORTE LOCAL", origem: 'Custo' },
    { codigo: '71102009', nome: "FRETES E CARRETOS", origem: 'Custo' },
    { codigo: '71102030', nome: "DESPACHANTE", origem: 'Custo' },
    { codigo: '71102034', nome: "DESPESAS COM COMBUSTIVEL", origem: 'Custo' },
    { codigo: '34104001', nome: "FRETES E CARRETOS", origem: 'Despesa' },
    { codigo: '34104003', nome: "SERVICOS ADUANEIROS", origem: 'Despesa' },
    { codigo: '34104004', nome: "DESPACHANTE", origem: 'Despesa' },
    { codigo: '34104031', nome: "DESPESAS COM COMBUSTIVEIS", origem: 'Despesa' },
    { codigo: '34202015', nome: "FRETES E CARRETOS", origem: 'Despesa' },
    { codigo: '34202029', nome: "DESPESAS COM COMBUSTIVEL", origem: 'Despesa' },
    { codigo: '34202032', nome: "DESPACHANTE", origem: 'Despesa' },
  ],
  servicos: [
    { codigo: '410302010', nome: "SERVICOS PRESTADOS PJ", origem: 'Custo' },
    { codigo: '410302020', nome: "SERVICOS PRESTADOS PF", origem: 'Custo' },
    { codigo: '410302030', nome: "SERVICO CONSULTORIA E ASSESSORIA", origem: 'Custo' },
    { codigo: '410305030', nome: "REPRESENTANTE COMERCIAL", origem: 'Custo' },
    { codigo: '410307010', nome: "ASSINATURAS", origem: 'Custo' },
    { codigo: '410307020', nome: "ANUNCIOS E EDITAIS", origem: 'Custo' },
    { codigo: '410307030', nome: "XEROX E ENCADERNACOES", origem: 'Custo' },
    { codigo: '410307050', nome: "CARTORIOS", origem: 'Custo' },
    { codigo: '410307120', nome: "SEGURANCA", origem: 'Custo' },
    { codigo: '410307240', nome: "ENTRETENIMENTO/LAZER", origem: 'Custo' },
    { codigo: '71102003', nome: "SERVICOS DE TERCEIROS - PJ", origem: 'Custo' },
    { codigo: '71102016', nome: "ASSESSORIAS E CONSULTORIAS", origem: 'Custo' },
    { codigo: '71102017', nome: "SERVICOS DE TERCEIROS - PESSOA FISICA", origem: 'Custo' },
    { codigo: '71102031', nome: "SEGURANCA E VIGILANCIA", origem: 'Custo' },
    { codigo: '34104013', nome: "SERVICOS DE TERCEIROS PESSOA JURIDICA", origem: 'Despesa' },
    { codigo: '34104019', nome: "SERVICO DE TERCEIRO PESSOA FISICA", origem: 'Despesa' },
    { codigo: '34104025', nome: "SEGURANCA - VIGILANCIA", origem: 'Despesa' },
    { codigo: '34104029', nome: "ASSESSORIAS E CONSULTORIAS", origem: 'Despesa' },
    { codigo: '34202010', nome: "SERVICOS DE TERCEIROS - PJ", origem: 'Despesa' },
    { codigo: '34202017', nome: "SERVICOS DE TERCEIROS - PESSOA FISICA", origem: 'Despesa' },
    { codigo: '34202023', nome: "SEGURANCA E VIGILANCIA", origem: 'Despesa' },
    { codigo: '34202027', nome: "ASSESSORIAS E CONSULTORIAS", origem: 'Despesa' },
  ],
  locacao: [
    { codigo: '410303050', nome: "TAXA DE CONDOMINIO", origem: 'Custo' },
    { codigo: '410304070', nome: "LEASING DE VEICULOS", origem: 'Custo' },
    { codigo: '410304080', nome: "ALUGUEL DE VEICULOS", origem: 'Custo' },
    { codigo: '410307100', nome: "LOCACOES", origem: 'Custo' },
    { codigo: '410307220', nome: "LEASING", origem: 'Custo' },
    { codigo: '410307350', nome: "DESP.COM CONDOMINIO", origem: 'Custo' },
    { codigo: '71102027', nome: "ALUGUEL", origem: 'Custo' },
    { codigo: '71102032', nome: "LOCACAO DE MAQUINAS E EQUIPAMENTOS", origem: 'Custo' },
    { codigo: '34104021', nome: "ALUGUEL A PESSOA FISICA", origem: 'Despesa' },
    { codigo: '34104027', nome: "LOCACAO DE MAQUINAS E EQUIPAMENTOS", origem: 'Despesa' },
    { codigo: '34104035', nome: "LOCACAO DE PESSOA JURIDICA", origem: 'Despesa' },
    { codigo: '34202019', nome: "ALUGUEL A PESSOA FISICA", origem: 'Despesa' },
    { codigo: '34202025', nome: "LOCACAO DE MAQ E EQUIPAMENTOS", origem: 'Despesa' },
    { codigo: '34202033', nome: "CONDOMINIOS DE IMOVEIS PROPRIOS", origem: 'Despesa' },
  ],
  impostos: [
    { codigo: '410304030', nome: "IPVA E LICENCIAMENTO", origem: 'Custo' },
    { codigo: '410307170', nome: "ASSOCIACAO DE CLASSE", origem: 'Custo' },
    { codigo: '410307180', nome: "CONTRIBUICAO INSTITUCIONAL", origem: 'Custo' },
    { codigo: '410307260', nome: "IMPOSTOS E TAXAS", origem: 'Custo' },
    { codigo: '410307330', nome: "IPTU", origem: 'Custo' },
    { codigo: '71102007', nome: "IMPOSTOS E TAXAS DIVERSAS", origem: 'Custo' },
    { codigo: '34104017', nome: "IMPOSTOS E TAXAS", origem: 'Despesa' },
    { codigo: '34104018', nome: "CONTRIBUICAO SINDICAL", origem: 'Despesa' },
    { codigo: '34202014', nome: "IMPOSTOS E TAXAS", origem: 'Despesa' },
    { codigo: '34202016', nome: "CONTRIBUICAO SINDICAL", origem: 'Despesa' },
    { codigo: '34202036', nome: "ROYALTIES", origem: 'Despesa' },
    { codigo: '34203006', nome: "IMPOSTOS E TAXAS", origem: 'Despesa' },
  ],
  viagens: [
    { codigo: '410305010', nome: "HOSPEDAGEM EM VIAGEM", origem: 'Custo' },
    { codigo: '410305020', nome: "DESPESA COM PASSAGEM", origem: 'Custo' },
    { codigo: '410305040', nome: "DESPESAS C/OVEBCOK", origem: 'Custo' },
    { codigo: '71102026', nome: "DESPESAS COM VIAGENS", origem: 'Custo' },
    { codigo: '34104020', nome: "DESPESAS COM VIAGENS", origem: 'Despesa' },
    { codigo: '34202018', nome: "DESPESAS COM VIAGENS", origem: 'Despesa' },
  ],
  depreciacao: [
    { codigo: '410307290', nome: "ENCARGOS COM DEPRECIACAO", origem: 'Custo' },
    { codigo: '71102008', nome: "ENCARGOS COM DEPRECIACAO", origem: 'Custo' },
    { codigo: '71102015', nome: "ENCARGOS DE DEPRECIACAO -CUSTO ATRIBUIDO", origem: 'Custo' },
    { codigo: '71102023', nome: "PIS-COFINS SOBRE DEPRECIACAO", origem: 'Custo' },
    { codigo: '34104014', nome: "ENCARGOS DE DEPRECIACAO", origem: 'Despesa' },
    { codigo: '34104022', nome: "PIS - COFINS SOBRE DEPRECIACAO", origem: 'Despesa' },
    { codigo: '34104026', nome: "DEPRECIACAO - CUSTO ATRIBUIDO", origem: 'Despesa' },
    { codigo: '34104034', nome: "DEPRECIACAO NAO DEDUTIVEL", origem: 'Despesa' },
    { codigo: '34202011', nome: "ENCARGOS COM DEPRECIACAO", origem: 'Despesa' },
    { codigo: '34202020', nome: "PIS / COFINS SOBRE A DEPRECIACAO", origem: 'Despesa' },
    { codigo: '34202024', nome: "ENCARGOS DE DEPRECIACAO -CUSTO ATRIBUIDO", origem: 'Despesa' },
  ],
};


export const TODAS_CONTAS_AGRICOLA = {};
Object.entries(PLANO_CONTAS_AGRICOLA).forEach(([pacoteId, contas]) => {
  contas.forEach((c) => { TODAS_CONTAS_AGRICOLA[c.codigo] = { ...c, pacoteId }; });
});

export const TODAS_CONTAS_RESORTS = {};
Object.entries(PLANO_CONTAS_RESORTS).forEach(([pacoteId, contas]) => {
  contas.forEach((c) => { TODAS_CONTAS_RESORTS[c.codigo] = { ...c, pacoteId }; });
});

// ---------------------------------------------------------------------------
// Corporativo — fonte oficial: Base_Corporativo.xlsx. A coluna de Centros de
// Custo é confiável (20 CCs, ver CCS_CORPORATIVO). A coluna de Contas
// Analíticas NÃO vem pareada por CC no arquivo-fonte (mesmo código de conta
// repetido em toda linha, só o nome da despesa muda). Decisão de 2026-08-16
// ("cada CC precisa conter todas as contas analíticas [...] mesma visão e
// layout da Têxtil, interpretando e separando a conta analítica por
// pacote"): todo CC recebe o mesmo plano de contas completo — as 21 contas
// reais da planilha (nenhuma inventada), agrupadas por pacote (agrupamento
// interpretado por mim, a planilha não separa por pacote). Espelho exato de
// frontend/src/OrcamentoARA.jsx (mesmos códigos sintéticos CORP01..CORP21).
// tipo: 'despesa' em todos os CCs — Corporativo não tem CC de produção.
// ---------------------------------------------------------------------------
export const CCS_CORPORATIVO = [
  { codigo: "0000102", nome: "Financeiro", tipo: 'despesa' },
  { codigo: "02", nome: "GSC (Arthur)", tipo: 'despesa' },
  { codigo: "0000104", nome: "Riscos, Auditoria e Compliance", tipo: 'despesa' },
  { codigo: "0000199", nome: "Conselho", tipo: 'despesa' },
  { codigo: "0010103", nome: "Contabilidade/Fiscal", tipo: 'despesa' },
  { codigo: "0010104", nome: "Departamento Pessoal", tipo: 'despesa' },
  { codigo: "0010105", nome: "TI GSP (SISTEMAS)", tipo: 'despesa' },
  { codigo: "0010107", nome: "COMPRAS", tipo: 'despesa' },
  { codigo: "0010109", nome: "NOVOS NEGÓCIOS", tipo: 'despesa' },
  { codigo: "0010110", nome: "AUDITORIA INTERNA", tipo: 'despesa' },
  { codigo: "0010111", nome: "Gestão de Pessoas", tipo: 'despesa' },
  { codigo: "0010112", nome: "Estratégia e Projetos", tipo: 'despesa' },
  { codigo: "0010114", nome: "Jurídico", tipo: 'despesa' },
  { codigo: "0010115", nome: "Escritório", tipo: 'despesa' },
  { codigo: "0010116", nome: "Controladoria", tipo: 'despesa' },
  { codigo: "0010117", nome: "TI GSI INFRA", tipo: 'despesa' },
  { codigo: "0010118", nome: "FP&A", tipo: 'despesa' },
  { codigo: "0010119", nome: "SECRETARIA DE GOVERNANÇA", tipo: 'despesa' },
  { codigo: "0010120", nome: "INOVAÇÃO E TECNOLOGIA", tipo: 'despesa' },
  { codigo: "0020102", nome: "MARKETING", tipo: 'despesa' },
];

export const PACOTES_CORPORATIVO = [
  { id: 'pessoal', nome: "Pessoal", ref: 'Base_Corporativo.xlsx (3 contas)' },
  { id: 'servicos', nome: "Serviços de Terceiros", ref: 'Base_Corporativo.xlsx (3 contas)' },
  // Nomenclatura padronizada em 2026-08-31 — espelho de frontend/src/OrcamentoARA.jsx.
  { id: 'locacao', nome: "Locação e Ocupação", ref: 'Base_Corporativo.xlsx (4 contas)' },
  { id: 'administrativo_utilidades', nome: "Administrativo e Utilidades", ref: 'Base_Corporativo.xlsx (6 contas)' },
  { id: 'manutencao', nome: "Manutenção", ref: 'Base_Corporativo.xlsx (1 conta)' },
  { id: 'comercial', nome: "Comercial e Marketing", ref: 'Base_Corporativo.xlsx (1 conta)' },
  { id: 'viagens', nome: "Viagens", ref: 'Base_Corporativo.xlsx (2 contas)' },
  { id: 'impostos', nome: "Impostos Indiretos e Diretos", ref: 'Base_Corporativo.xlsx (1 conta)' },
];

export const PLANO_CONTAS_CORPORATIVO = {
  // Consultórias PJs (2026-08-23) — espelho de frontend/src/OrcamentoARA.jsx
  // (ver nota completa lá): CORP03 sai de 'servicos' e vira a 2ª conta
  // analítica editável de Pessoal, só no Corporativo.
  pessoal: [
    { codigo: 'CORP01', nome: "Salários /Despesas com o pessoal", origem: 'Despesa' },
    { codigo: 'CORP13', nome: "Cursos e treinamentos", origem: 'Despesa' },
    { codigo: 'CORP03', nome: "Consultórias PJs", origem: 'Despesa' },
  ],
  servicos: [
    { codigo: 'CORP02', nome: "Assessorias e Consultorias", origem: 'Despesa' },
    { codigo: 'CORP04', nome: "Projetos", origem: 'Despesa' },
    { codigo: 'CORP08', nome: "Honorários Advocatícios", origem: 'Despesa' },
  ],
  locacao: [
    { codigo: 'CORP05', nome: "Aluguel e Condomínio", origem: 'Despesa' },
    { codigo: 'CORP09', nome: "Telefonia e Internet", origem: 'Despesa' },
    { codigo: 'CORP10', nome: "Locação de Software", origem: 'Despesa' },
    { codigo: 'CORP20', nome: "Locação de equipamentos", origem: 'Despesa' },
  ],
  administrativo_utilidades: [
    { codigo: 'CORP06', nome: "Material de expediente", origem: 'Despesa' },
    { codigo: 'CORP11', nome: "Material de Informática", origem: 'Despesa' },
    { codigo: 'CORP15', nome: "Eventos e Confraternizações", origem: 'Despesa' },
    { codigo: 'CORP16', nome: "Caixa Fundo fixo", origem: 'Despesa' },
    { codigo: 'CORP17', nome: "Despesas Diversas", origem: 'Despesa' },
    { codigo: 'CORP19', nome: "Material de Copa/Cozinha e limpeza", origem: 'Despesa' },
  ],
  manutencao: [
    { codigo: 'CORP07', nome: "Reformas e Manutenção", origem: 'Despesa' },
  ],
  comercial: [
    { codigo: 'CORP12', nome: "Propaganda e Publicidade", origem: 'Despesa' },
  ],
  viagens: [
    { codigo: 'CORP14', nome: "Combustível/Alimentação/Transporte", origem: 'Despesa' },
    { codigo: 'CORP18', nome: "Passagem e Hospedagem", origem: 'Despesa' },
  ],
  impostos: [
    { codigo: 'CORP21', nome: "Impostos e taxas", origem: 'Despesa' },
  ],
};

export const TODAS_CONTAS_CORPORATIVO = {};
Object.entries(PLANO_CONTAS_CORPORATIVO).forEach(([pacoteId, contas]) => {
  contas.forEach((c) => { TODAS_CONTAS_CORPORATIVO[c.codigo] = { ...c, pacoteId }; });
});
